//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G1_Website_Tour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.bill_detail = new HashSet<bill_detail>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public double total { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> Staffid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_detail> bill_detail { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual user user { get; set; }
    }
}
