//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G1_Website_Tour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_detail
    {
        public int bill_id { get; set; }
        public int tour_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual tour tour { get; set; }
    }
}
