//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G1_Website_Tour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tour()
        {
            this.bill_detail = new HashSet<bill_detail>();
        }
    
        public int id { get; set; }
        public string name_tour { get; set; }
        public Nullable<System.DateTime> start_tour { get; set; }
        public Nullable<System.DateTime> end_tour { get; set; }
        public string description_tour { get; set; }
        public string image_tour { get; set; }
        public long price { get; set; }
        public int vehicle_id { get; set; }
        public string type_id { get; set; }
        public Nullable<System.DateTime> DateOfManufacture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_detail> bill_detail { get; set; }
        public virtual Type_Tour Type_Tour { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
